spring:
  session:
    jdbc:
      table-name: "user_session"
    timeout: 604800
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/tvmedicine
    username: postgres
    password: superpassword132
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  servlet:
    session:
      cookie:
        name: SESSIONID
  port: 80